services:
    frontend:
        container_name: frontend
        build: ./frontend
        image: frontend
        restart: on-failure
        env_file:
            - ./frontend/.env-frontend
        ports:
            - "3000:3000"
        networks:
            - agricultural-network
        volumes:
            - ./frontend/app:/app/
            - /app/node_modules
    
    backend:
        container_name: backend
        build: ./backend/
        image: backend
        restart: on-failure
        env_file:
            - .env
        ports:
            - "8080:8080"
        networks:
            - agricultural-network
        volumes:
            - ./backend/src/:/code/

networks:
    agricultural-network:
        name: agricultural-network

volumes:
    media: