# Generated by Django 5.2.3 on 2025-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
